Repository wecode-bootcamp-korea/27-1st-weasley-backend, pull requests merged in 2021-12, with the labels that each got.

#3 [CREATED] 인가를 위한 core app의 utils.authorization 작성
  core/utils.py
Labels: Status: 리뷰 요청

#4 [MODIFIED] 제품의 태그 정보 다대다 필드로 변경
  products/migrations/0002_auto_20211201_1343.py
  products/models.py
Labels: Status: 리뷰 요청

#2 [CREATED] 다양한 값의 검증을 위한 core.validators 작성
  products/validators.py
  shops/validators.py
  users/validators.py
Labels: Status: 리뷰 요청

#8 [MODIFIED] modified phone regex miss writing
  users/validators.py
Labels: Status: 리뷰 요청

#5 [CREATED] 로그인을 위한 유저 존재여부 확인 뷰 및 로그인 뷰
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#6 [CREATED] created user check view
  users/models.py
  users/views.py
Labels: Status: Accepted

#10 [MODIFIED] minor update -> changed urls.py user.signinview
  users/urls.py
  weasley/urls.py
Labels: Status: 리뷰 요청

#11 [MODIFIED] minor update -> changed urls.py for products app
  weasley/urls.py
Labels: Status: 리뷰 요청

#9 [Created] 회원가입 기능 signup view 구현
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#14 [Modified] minor fix with jwt
  users/views.py
Labels: Status: 리뷰 요청

#13 [MODIFIED] minor update -> add csv_input.py at gitignore
  .gitignore
Labels: Status: 리뷰 요청

#7 [CREATED] 유저의 장바구니 정보를 가져오는 뷰 작성
  .gitignore
  shops/urls.py
  shops/views.py
  weasley/settings.py
  weasley/urls.py
Labels: Status: Conflict 해결 요청

#15 [CREATED] 카트에 담긴 제품의 수량을 바꾸기 위한 patch 메소드 구현
  shops/urls.py
  shops/views.py
Labels: Status: Accepted

#17 [CREATED] 장바구니에 물건 추가를 위한 post 메소드 구현
  shops/urls.py
  shops/views.py
Labels: Status: 리뷰 요청

#16 [CREATED] CartView의 delete 메소드 추가
  shops/views.py
Labels: Status: 리뷰 요청

#19 [MODIFIED] URL 파라미터의 인자를 cart_id로 변경
  shops/urls.py
  shops/views.py
Labels: Status: 리뷰 요청

#21 [MODIFIED] 장바구니 get시 반환하는 정보 추가
  shops/views.py
Labels: Status: Conflict 해결 요청

#23 [CREATED] 회원의 주소록 조회 기능 구현
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#26 [CREATED] 리뷰 작성 기능 구현
  products/urls.py
  products/validators.py
  products/views.py
Labels: Status: 리뷰 요청

#22 [CREATED] 주문 정보를 조회하기 위한 get 메소드 구현(all/specifig)
  shops/urls.py
  shops/views.py
Labels: Status: 리뷰 요청

#24 [CREATED] 유저의 주소록에 주소 정보를 추가하기 위한 post 메소드 작성
  users/views.py
Labels: Status: 리뷰 요청

#25 [CREATED] 주문을 진행하기 위한 OrderView POST 메소드 구현
  shops/models.py
  shops/urls.py
  shops/views.py
Labels: Status: 리뷰 요청

#20 [CREATED] '상품보기' 페이지를 위한 get 메소드 구현
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20211201_1343.py
  products/urls.py
  products/validators.py
  products/views.py
  shops/migrations/0001_initial.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#29 [MODIFIED] concat seperated class
  shops/views.py
Labels: Status: 리뷰 요청

#31 [MODIFIED] MINOR UPDATE - add gunicorn on requirements.txt
  requirements/requirements.txt
Labels: Status: 리뷰 요청

#32 [MODIFIED] MINOR UPDATE add Dockerfile on .gitignore
  .gitignore
Labels: Status: 리뷰 요청

#30 [CREATED] 구독 조회를 위한 엔드포인트
  2
  shops/urls.py
  shops/views.py
Labels: Status: 리뷰 요청

#33 [CREATED] 구독 신청 기능 구현
  shops/views.py
Labels: Status: 리뷰 요청

#36 MODIFIED / hot fix bug fixed
  shops/views.py
Labels: Status: 리뷰 요청

#35 [CREATED] 구독 삭제 기능 구현
  shops/views.py
Labels: Status: 리뷰 요청

#38 [MODIFIED] add subscribe id
  shops/views.py
Labels: Status: 리뷰 요청

#37 [CREATED] 구독 중인 상품의 주기를 변경하기 위한 PATCH 메소드 구현
  shops/views.py
Labels: Status: 리뷰 요청

#40 MODIFIED / remove dockerfile from .gitignore
  .gitignore
  Dockerfile.web
Labels: Status: 리뷰 요청

#41 [CREATED] 스케쥴러 도커 파일 추가 및 README.md 추가
  Dockerfile.scheduler
  README.md
Labels: Status: Accepted
